#server:
#  url:
#    websocket: ws://localhost:9020/verizon/dm/alerts
com:
  nomis:
    serviceType: OPTIMIZATION #upper case is mandatory, because it will be converted to enum ActionType.SIMULATION by Spring with enum::valueOf() method

com.rednavis:
      socket:
        protocol: http://
        port: 9010
        host: localhost
        apiPath: /api/jobs
        connectUrl: ${com.rednavis.socket.protocol}${com.rednavis.socket.host}:${com.rednavis.socket.port}${com.rednavis.socket.apiPath}

spring:
  rabbitmq:
    #amqpHost: 192.168.50.142
    amqpHost: 127.0.0.1
    amqpPort: 5672
#    connection-timeout: 5000
    amqpUser: test
    amqpPassword: test
    topic.exchange: nomis.services
    routingKey: baseline
    simulationResponseQueue: simResponseQueue
    optimizationResponseQueue: optResponseQueue
    baselineResponseQueue: basResponseQueue
    statusQueue: nomisStatusQueue
    configQueue: nomisConfigQueue
    logQueue: logmessages

#com:
#    nomis:
#        serviceType: SIMULATION #upper case is mandatory, because it will be converted to enum ActionType.SIMULATION by Spring with enum::valueOf() method
#com:
#  nomis:
#    serviceType: BASELINE #upper case is mandatory, because it will be converted to enum ActionType.BASELINE by Spring with enum::valueOf() method
#com:
#  nomis:
#    serviceType: NOMISSERVICES #upper case is mandatory, because it will be converted to enum ActionType.SIMULATION by Spring with enum::valueOf() method



